/**
 * Enums mirrored from the backend Prisma schema (Phase 6.1 decision F8).
 * Declared as const objects + string-literal unions so they carry runtime
 * values without TypeScript `enum` semantics. Kept in lockstep with the
 * backend — never redesigned here.
 */

export const AccountStatus = {
  ACTIVE: 'ACTIVE',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  SUSPENDED: 'SUSPENDED',
  DELETED: 'DELETED',
} as const;
export type AccountStatus = (typeof AccountStatus)[keyof typeof AccountStatus];

export const UserRole = {
  USER: 'USER',
  TEACHER: 'TEACHER',
  ADMIN: 'ADMIN',
} as const;
export type UserRole = (typeof UserRole)[keyof typeof UserRole];

export const Language = {
  ENGLISH: 'ENGLISH',
  UKRAINIAN: 'UKRAINIAN',
} as const;
export type Language = (typeof Language)[keyof typeof Language];

export const Theme = {
  DARK: 'DARK',
} as const;
export type Theme = (typeof Theme)[keyof typeof Theme];

export const AvatarType = {
  PREDEFINED: 'PREDEFINED',
  CUSTOM_UPLOAD: 'CUSTOM_UPLOAD',
} as const;
export type AvatarType = (typeof AvatarType)[keyof typeof AvatarType];

export const QuestionType = {
  SINGLE_CHOICE: 'SINGLE_CHOICE',
  MATCHING: 'MATCHING',
} as const;
export type QuestionType = (typeof QuestionType)[keyof typeof QuestionType];

export const Difficulty = {
  BEGINNER: 'BEGINNER',
  INTERMEDIATE: 'INTERMEDIATE',
  ADVANCED: 'ADVANCED',
} as const;
export type Difficulty = (typeof Difficulty)[keyof typeof Difficulty];

export const QuizType = {
  SUBJECT_QUIZ: 'SUBJECT_QUIZ',
  RANDOM_QUIZ: 'RANDOM_QUIZ',
  DUEL: 'DUEL',
  MOCK_EXAM: 'MOCK_EXAM',
} as const;
export type QuizType = (typeof QuizType)[keyof typeof QuizType];

/**
 * The quiz modes an administrator may author as a stored Quiz — mirrors the
 * backend's AUTHORABLE_QUIZ_MODES exactly.
 *
 * DUEL and MOCK_EXAM are deliberately absent. Both are generated by their own
 * endpoints under conditions that are not negotiable — a mock's whole value is
 * that its paper cannot be configured — so neither is authorable, and the
 * admin UI must not offer them.
 *
 * Spelled out as values rather than derived from QuizType on purpose: adding a
 * mode to the enum must not silently widen what an administrator can create.
 */
export const AUTHORABLE_QUIZ_MODES = [QuizType.SUBJECT_QUIZ, QuizType.RANDOM_QUIZ] as const;
export type AuthorableQuizMode = (typeof AUTHORABLE_QUIZ_MODES)[number];

export const DuelMode = {
  /** Both sit the same paper whenever they like; the result is a comparison. */
  ASYNC: 'ASYNC',
  /** Both on the clock together, question by question. Not built yet. */
  LIVE: 'LIVE',
} as const;
export type DuelMode = (typeof DuelMode)[keyof typeof DuelMode];

export const DuelStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
  COMPLETED: 'COMPLETED',
  EXPIRED: 'EXPIRED',
} as const;
export type DuelStatus = (typeof DuelStatus)[keyof typeof DuelStatus];

export const QuizStatus = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
} as const;
export type QuizStatus = (typeof QuizStatus)[keyof typeof QuizStatus];
